### PR TITLE
Use $app->end instead of die on redirect

### PR DESCRIPTION
**Pull request by stevepsharpe**
Hey there!

I was getting blank pages on redirects. I swapped out the `die()` for `Craft::$app->end()` and it works as expected. Cheers!

### CODE REVIEW

**Comment by sbossarte** [comment]
@stevepsharpe This must have slipped under the radar after a reference to `die()` versus `Craft::$app->end()` happened in https://github.com/charliedevelopment/craft3-fallback-site/pull/2

Thanks for the pull request.

**Comment by stevepsharpe** [comment]
Awesome @sbossarte. Do you plan on releasing 1.2.2? Would be great so we can update our dependencies.

**Comment by sbossarte** [comment]
@stevepsharpe Got the new release up.

**Comment by stevepsharpe** [comment]
That's great, thanks again @sbossarte :)

**Pull request merged**
